### ISSUE TITLE
Multiple accessories

### ISSUE THREAD

**Issue by mengds2016** [NN708/ESP-Homekit-IRHub#9]
How many accessories are supported at most?Bridge must be used?

**Comment by NN708** [comment]
Hi, @mengds2016 

The IR Hub does not need another bridge because it is the bridge itself to connect Homekit and IR.

Multiple accessories can be supported. However, at present I don't know the max number of accessories can be supported (because now we only have 2 accessories...) It depends on the Flash and RAM size. I think perhaps 5 to 10 should be OK.

**Comment by NN708** [comment]
The issue is now closed. Don't hesitate to re-open it if you still have the issue.
